name: trashy_road
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  clock: ^1.1.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flame_behaviors: ^1.1.0
  flame_bloc: ^1.11.0
  flame_tiled: ^1.19.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.4.0
  meta: ^1.10.0
  path: ^1.8.3
  rive: ^0.12.4
  tiled: ^0.10.2

dev_dependencies:
  build_runner: null
  flame_test: ^1.15.4
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

# pubspec.yaml
# ...
flutter_gen:
  integrations:
    rive: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tiles/
    - assets/images/
    - assets/rive/
