name: tiled_map_parser
description: Prepares a Tiled map file (`.tmx`) for use with Flame.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason_logger: ^0.2.11
  path: ^1.9.0
  xml: ^6.5.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
